#pragma once
#include <stdint.h>

// Anti-aliased proportional fonts.
//
// The 8x16 console font (header/font.h) stays where it belongs: window
// chrome, the terminal, and <pre>/<code>, all of which want a fixed cell.
// Prose does not. Rendering a page in a monospace face is the single largest
// reason the browser reads as a terminal showing a document rather than as a
// browser, so page text is drawn from these faces instead.
//
// A glyph is a rectangle of coverage bytes, not a bitmask: 0 is untouched and
// 255 is the full text colour, and gfx blends the values between. That costs
// a byte per pixel of .rodata rather than a bit, which is the trade this
// project can afford far more easily than it can afford unreadable 1-bit
// text at 17px on a dark background.
//
// Tables are generated by tools/mkfontprop.py -- see src/fontprop.c.

#define PF_FIRST    32          // first character in the tables
#define PF_LAST     126         // last, inclusive
#define PF_GLYPH_N  (PF_LAST - PF_FIRST + 1)

typedef struct {
    uint8_t  adv;               // pen advance in pixels
    uint8_t  w, h;              // coverage rectangle size (0 for blanks)
    int8_t   left;              // x offset from the pen to the rectangle
    int8_t   top;               // y offset from the line-box top
    uint32_t off;               // start of the rectangle in the face's cov[]
} pf_glyph_t;

typedef struct {
    uint8_t           height;   // line-box height, already includes leading
    uint8_t           ascent;   // baseline measured from the line-box top
    const pf_glyph_t* glyphs;
    const uint8_t*    cov;
} pf_face_t;

extern const pf_face_t pf_body;
extern const pf_face_t pf_body_bold;
extern const pf_face_t pf_body_italic;
extern const pf_face_t pf_h3;
extern const pf_face_t pf_h2;
extern const pf_face_t pf_h1;
