#pragma once
#include <stdint.h>

// 8x16 bitmap font: font8x16[c][row], MSB = leftmost pixel. Generated by
// tools/mkfont.py from the Lat15-VGA16 console font — see src/font8x16.c.
#define FONT_W 8
#define FONT_H 16

extern const uint8_t font8x16[256][16];
